# clientname:                    Unique name for application instance
clientname: brave_worker

# no-program-tasks:              Disable executing of PROGRAM tasks
no-program-tasks: true

# - PostgreSQL Connection Credentials -
connection:
  # dbname:                        PG config DB dbname (default: timetable)
  dbname: my_database
  # host:                          PG config DB host (default: localhost)
  host: my_host
  # user:                          PG config DB user (default: scheduler)
  user: scheduler_role
  # password:                      PG config DB password
  password: very_strong_one
  # pgurl:                         PostgreSQL connection URL (optional, will override any conflicting command line options)
  pgurl: postgres://scheduler_role@my_host/my_database
  # port:                          PG config DB port (default: 5432) 
  port: 5433
  # sslmode:[disable|require]      What SSL priority use for connection
  sslmode: require
  # timeout:                       PostgreSQL connection timeout in seconds (default: 90)
  timeout: 45

# - Logging Settings -
logging:
  # log-level:[debug|info|error]   Verbosity level for stdout and log file (default: info)
  log-level: debug
  # log-database-level:[debug|info|error|none]  Verbosity level for database storing (default: info)
  log-database-level: debug
  # log-file:                      File name to store logs
  log-file: session.log
  # log-file-format:[json|text]    Format of file logs (default: json)
  log-file-format: text
  # log-file-rotate                Rotate log files
  log-file-rotate: true
  # log-file-size:                 Maximum size in MB of the log file before it gets rotated (default: 100)
  log-file-size: 10
  # log-file-age:                  Number of days to retain old log files, 0 means forever (default: 0)
  log-file-age: 28
  # log-file-number:               Maximum number of old log files to retain, 0 to retain all (default: 0)
  log-file-number: 10

# - Bootstrap Settings -
start:
  # debug                          Run in debug mode. Only asynchronous chains will be executed
  debug: false
  # file:                          SQL script file to execute during startup
  file: ""
  # init:                          Initialize database schema to the latest version and exit
  init: false
  # upgrade:                       Upgrade database to the latest version
  upgrade: true

# - Resource Settings -
resource:
  # cron-workers:                  Number of parallel workers for scheduled chains (default: 16)
  cron-workers: 10
  # interval-workers:              Number of parallel workers for interval chains (default: 16)
  interval-workers: 6
  # chain-timeout:                 Abort any chain that takes more than the specified number of milliseconds
  chain-timeout: 0
  # task-timeout:                  Abort any task within a chain that takes more than the specified number of milliseconds
  task-timeout: 0  

# - REST API Settings -
rest:
  # rest-port:                     REST API port (default: 0)
  rest-port: 8008
